### ISSUE TITLE
A small bug in sample_script.jl

### ISSUE THREAD

**Issue by dbai1989** [SotaYoshida/NuclearToolkit.jl#21]
Yoshida-san, thanks for sharing this powerful julia package! I have installed it successfully on my MacBook. 

I notice a small bug in sample_script.jl (maybe you have noticed it already). The uncommented line "sntf="tbme_emn500n4lo_2n3n_srg2.0hw"*string(hw)*"emax"*string(emax)*".snt.bin"" is actually not compatile with this version of NuclearToolkit.jl, and it is the commented line "#sntf = "tbme_em500n3lo_srg2.0hw"*string(hw)*"emax"*string(emax)*".snt.bin"" that should be used. 

When corrected, the sample_script.jl could be run successfully.

**Comment by SotaYoshida** [comment]
Hi @dbai1989
Thank you for trying the package and letting me know the bug!
You are right. That line was inconsistent to the `optional_parameters.jl`. I've corrected it.
Thanks again!!
