### ISSUE TITLE
reference to global calc_3N

### ISSUE THREAD

**Issue by mdavezac** [SotaYoshida/NuclearToolkit.jl#23]
I'm guessing the line below should not reference some global value, but rather chiEFTobj?

https://github.com/SotaYoshida/NuclearToolkit.jl/blob/e77863fa1adf9ea884ea17a54d588763ec74f93e/src/chiEFTint/main_chiEFTint.jl#L69

Referencing openjournals/joss-reviews#4665.

**Comment by SotaYoshida** [comment]
@mdavezac Thank you very much for your time and reviewing the code.

Absolutely you are right.
If it is OK to modify the code during the review process, I will correct it.
Related question at our [REVIEW] [here] (https://github.com/openjournals/joss-reviews/issues/4694#issuecomment-1221663351)

Thanks.

**Comment by mdavezac** [comment]
My understanding is that making the code and software better is the point of the review process. So that would be an emphatic yes.

**Comment by SotaYoshida** [comment]
@mdavezac Thanks.
I have fixed the bug (and made some improvements in terms of performance). #24
