### ISSUE TITLE
[JOSS Review] use doi's and links for arXiv references

### ISSUE THREAD

**Issue by villaa** [SotaYoshida/NuclearToolkit.jl#31]
Several references in the reference list do not list links or DOIs, but there are papers on arXiv which gives links/DOIs. I suggest using the style found in the paper [here](https://joss.theoj.org/papers/10.21105/joss.03725) for those references. 

The references are:

Bezanson, J., Karpinski, S., Shah, V. B., & Edelman, A. (2012). Julia: A fast dynamic45
language for technical computing. arXiv Preprint arXiv:1209.5145.

Johnson, C. W., Ormand, W. E., McElvain, K. S., & Shan, H. (2018). BIGSTICK: A flexible64
configuration-interaction shell-model code.

Shimizu, N. (2013). Nuclear shell-model code for massive parallel computation, ”KSHELL”.

Yoshida, S. (2022). Exploring medium mass nuclei using effective chiral nucleon-nucleon86
interactions. arXiv Preprint arXiv:2208.02464.

**Comment by SotaYoshida** [comment]
Thanks again. I hope the DOIs are now properly added.
https://github.com/openjournals/joss-reviews/issues/4694#issuecomment-1266316048

**Comment by villaa** [comment]
> Thanks again. I hope the DOIs are now properly added. [openjournals/joss-reviews#4694 (comment)](https://github.com/openjournals/joss-reviews/issues/4694#issuecomment-1266316048)

Yes, they look good now. I think this issue can be closed--I don't know if you want to do a pull request. I often try to make pull requests and issues 1-to-1 thanks to a suggestion from my first JOSS review. 

If you want to do that: make a pull request from the branch that you have this fix on and include this issue as  being addressed by that request. Then they are linked and you can close both at the same time.
