### ISSUE TITLE
[JOSS Review] Installation and example usage failures

### ISSUE THREAD

**Issue by villaa** [SotaYoshida/NuclearToolkit.jl#33]
I had a hard time telling if the installation was successful following the documentation. I opened a `Julia` prompt and typed:

```julia>using Pkg; Pkg.add("NuclearToolkit")```

It completed many tasks seemingly without error. After this the following directory existed:

```~/.julia/packages/NuclearToolkit/```

I took this as evidence of success. But it would be better to have perhaps a script that checks the installation and is clear about if it is OK. Maybe such a script exists in `tests/` but I could not find in the documentation what test to run. 

I tried to run the `sample_script.jl` as well. In a **separate terminal** I ran the following from the command line:

```julia -t 10 sample_script.jl```

I received the following error:

```
chi_order must be <= 3 for pottype=emn500n3lo or em500n3lo, chi_order=3 will be used
ERROR: LoadError: KeyError: key "E_3F2" not found
```

followed by a stack trace.

**Comment by villaa** [comment]
Note: I am using macOS 12.6 on a MacBook Pro with M1 chip.

**Comment by SotaYoshida** [comment]
@villaa Thank you so much for reviewing the code.

In the `src/chiEFTint/struct_const_io.jl` there is a bug related to this issue:
```julia
    if (params.pottype =="emn500n3lo" || params.pottype =="em500n3lo") && params.chi_order > 3
        println("chi_order must be <= 3 for pottype=emn500n3lo or em500n3lo, chi_order=3 will be used")
        params.chi_order=4 #this must be 3
    end
```

I have fixed the bug and will release it soon.

**Comment by rkurchin** [comment]
Hi, JOSS editor checking in on this! Has this bug been fixed? I don't see a linked PR, but perhaps it was part of something else and this issue got orphaned?

(linking to [review issue](https://github.com/openjournals/joss-reviews/issues/4694))

**Comment by villaa** [comment]
I can't tell if this issue has been resolved on the main branch in the latest release. I'll have to update and test it explicitly tomorrow.

**Comment by SotaYoshida** [comment]
Sorry for lack of explanation.
This problem was fixed at the commit 4855ed062067137cff0687a0aef662cb950edb82 (versions >= 2.0.2).

Thank you for your time.

**Comment by villaa** [comment]
Ok, I was now able to generate output, I guess the last thing I would ask is that the expected result of `julia -t 10 sample_script.jl` be stored in a file in the repository and linked to the documentation, giving the expected md5 checksum. 

This is because I ran the program, it appears to have run correctly, but I am struggling to figure out if the output is correct.

**Comment by SotaYoshida** [comment]
@villaa Thanks again.

> I would ask is that the expected result of julia -t 10 sample_script.jl be stored in a file in the repository and linked to the documentation, giving the expected md5 checksum.

I appreciate this suggestion. 
The `sample_script.jl` in the repository slightly overlap in their significance with the test code [test/runtests.jl](https://github.com/SotaYoshida/NuclearToolkit.jl/tree/main/test/runtests.jl).
They, `sample_script.jl` and `test/runtests.jl`, are doing similar jobs using **different parameters**,
but it may be good to leave the former one as it is (to provide users with another template to work with the package).

Then, I have moved the sample_script.jl to `example/` and added a new workflow for Github Actions, which pushes the results of `example/sample_script.jl` to [example/log_sample_script.txt](https://github.com/SotaYoshida/NuclearToolkit.jl/blob/develop/example/log_sample_script.txt) on any commits.
Now one can see the expected output in the repository and the corresponding hash, and the link to `log_sample_script.txt` is also available from the corresponding [document](https://sotayoshida.github.io/NuclearToolkit.jl/dev/#Installation-and-example).

#57 #58 The latest release is now v.0.2.4.

**Comment by villaa** [comment]
@SotaYoshida great, I am ready to sign off on the submission--you can close the two issues I had opened.

**Comment by SotaYoshida** [comment]
@villaa Thank you so much for your comments.
