### ISSUE TITLE
chiEFTint potential for Sn132 region

### ISSUE THREAD

**Issue by hamad12a** [SotaYoshida/NuclearToolkit.jl#96]
1)  [Edited] I was able to run the code setting Sn100 as the core but Sn132 fails to proceed `target: Sn132 Ref. => Z=50 N=82 warn! Nocc` due to what I suspect is the setting of representation. I am quite not sure about whether the code supports particle-hole representation. For my purpose which is structural calculations around Sn132 closed core, I need particle-hole representation to set the core on Sn132, the s.p.e are of Sn131, the s.h.e are of Sb133.

2) The second separate point I'm very in need is am working with Antoine code which requires the matrix to be in a format different from Kshell (snt format), is there a feature to convert between the two or a direct option to output the interaction matrix in Antoine format?

Your feedback is appreciated!

**Comment by SotaYoshida** [comment]
Hi @hamad12a

1. The shell-model part of this package is not designed to work with Z != N core or model spaces having multi-major shells.

2. NO.
FYI, a Python script, which translates NuShellX/OXBASH format into snt (KSHELL) format, is provided in [KSHELL](https://sites.google.com/alumni.tsukuba.ac.jp/kshell-nuclear/d).
If you have any scripts to transform ANTOINE inputs to NuShellX, you can try them.

**Comment by hamad12a** [comment]
@SotaYoshida Thank you for your response!

Let me dictate if what I know is correct.

The shell-model calculations which I understand is the final step to diagonalize a given hamiltonian (s.p.e + eff_int) in a given model space (core+valence space). Because the effective interaction is obtained after being adapted to a chosen model space by means of perturbation theory (Q-boxes, G-matrix, etc.) which is the second part in the code I believe (HFMBPT & VS-IMSRG calculation). The step before would be the renormalization of the N3LO potential up to a chosen order (generate NN free-medium potential or obtaining chiEFTint potential).

I don't intend to perform any shell-model calculation except the TBMEs interaction for nuclei around Sn132 core
such that the valence space of protons being particles while the neutrons being holes. Is that possible?

**Comment by SotaYoshida** [comment]
@hamad12a 
>For my purpose which is structural calculations around Sn132 closed core, I need particle-hole representation to set the core on Sn132, the s.p.e are of Sn131, the s.h.e are of Sb133.

Sorry, I missed your point in the previous post.
> valence space of protons being particles while the neutrons being holes. Is that possible?
As far as my package is concerned, there is no feature to deal with particle-hole interaction.

We can implement it, but I will not make it. One reason is personal, i.e. I do have not much time these days.
And the second one is that the shell-model code in this package is intended to be used not for cutting-edge problems, but for testing new algorithms, emulators, quantum computing, machine-learning, etc. 
For your purposes, I recommend you to consider other shell-model codes on the market.

**Comment by hamad12a** [comment]
> el code in this package is

I understand your busyness, but if you provide hints or road map regarding this point I may work on this!
